default: file

drivers:
  console:
    format: text

  file:
    path: logs/logs.log
    format: json

  sql:
    driver: 'mysql'
    host: 'localhost'
    dbname: 'telemetry'
    username: 'root'
    password: 'password'
    charset: 'utf8'
    table: 'logs'